fix:修缮漏洞

diff --git a/ezdown b/ezdown
--- a/ezdown
+++ b/ezdown
@@ -269,17 +269,17 @@ function get_kubeasz() {
   # check if kubeasz already existed
   [[ -d "$BASE/roles/kube-node" ]] && { logger warn "kubeasz already existed"; return 0; }
 
-  if [[ ! -f "$imageDir/kubeasz_$KUBEASZ_VER.tar" ]];then
-    logger info "downloading kubeasz: $KUBEASZ_VER"
-    docker pull "easzlab/kubeasz:$KUBEASZ_VER" && \
-    docker save -o "$imageDir/kubeasz_$KUBEASZ_VER.tar" "easzlab/kubeasz:$KUBEASZ_VER"
+  if [[ ! -f "$imageDir/kubeasz_$KUBEASZ_VER-jh4j.tar" ]];then
+    logger info "downloading kubeasz: $KUBEASZ_VER-jh4j"
+    docker pull "harbor.nisco.cn/easzlab/kubeasz:$KUBEASZ_VER-jh4j" && \
+    docker save -o "$imageDir/kubeasz_$KUBEASZ_VER-jh4j.tar" "harbor.nisco.cn/easzlab/kubeasz:$KUBEASZ_VER-jh4j"
   else
-    docker load -i "$imageDir/kubeasz_$KUBEASZ_VER.tar"
+    docker load -i "$imageDir/kubeasz_$KUBEASZ_VER-jh4j.tar"
   fi
 
   docker ps -a |grep -q temp_easz && { logger debug "remove existing container"; docker rm -f temp_easz; }
   logger debug " run a temporary container"
-  docker run -d --name temp_easz easzlab/kubeasz:${KUBEASZ_VER} || { logger error "failed."; exit 1; }
+  docker run -d --name temp_easz harbor.nisco.cn/easzlab/kubeasz:${KUBEASZ_VER}-jh4j || { logger error "failed."; exit 1; }
 
   [[ -d "$BASE/down" ]] && /bin/mv -f "$BASE/down" /tmp
   [[ -d "$BASE/bin" ]] && /bin/mv -f "$BASE/bin" /tmp
@@ -678,12 +678,12 @@ function start_kubeasz_docker() {
   docker ps -a --format="{{ .Names }}"|grep kubeasz > /dev/null 2>&1 && \
   docker rm -f kubeasz > /dev/null
 
-  if [[ ! -f "$imageDir/kubeasz_$KUBEASZ_VER.tar" ]];then
-    logger info "downloading kubeasz: $KUBEASZ_VER"
-    docker pull "harbor.nisco.cn/easzlab/kubeasz:$KUBEASZ_VER" && \
-    docker save -o "$imageDir/kubeasz_$KUBEASZ_VER.tar" "harbor.nisco.cn/easzlab/kubeasz:$KUBEASZ_VER"
+  if [[ ! -f "$imageDir/kubeasz_$KUBEASZ_VER-jh4j.tar" ]];then
+    logger info "downloading kubeasz: $KUBEASZ_VER-jh4j"
+    docker pull "harbor.nisco.cn/easzlab/kubeasz:$KUBEASZ_VER-jh4j" && \
+    docker save -o "$imageDir/kubeasz_$KUBEASZ_VER-jh4j.tar" "harbor.nisco.cn/easzlab/kubeasz:$KUBEASZ_VER-jh4j"
   else
-    docker load -i "$imageDir/kubeasz_$KUBEASZ_VER.tar"
+    docker load -i "$imageDir/kubeasz_$KUBEASZ_VER-jh4j.tar"
   fi
 
   logger info "try to run kubeasz in a container"
@@ -710,7 +710,7 @@ function start_kubeasz_docker() {
       --volume /root/.kube:/root/.kube \
       --volume /root/.ssh:/root/.ssh \
       --volume /etc/docker:/etc/docker \
-      harbor.nisco.cn/easzlab/kubeasz:${KUBEASZ_VER}
+      harbor.nisco.cn/easzlab/kubeasz:${KUBEASZ_VER}-jh4j
 }
 
 function clean_container() {
